name: intro_pymc

channels:
  - conda-forge
dependencies:
  - python
  - altair
  - blackjax
  - ipython
  - hvplot
  - ipywidgets
  - jax
  - jupyter_bokeh
  - jupyter_client
  - jupyter_core
  - jupyterlab
  - numba
  - nutpie
  - pandas
  - patsy
  - pip
  - plotly
  - polars
  - preliz
  - pyarrow
  - pymc
  - pymc-extras
  - pydot
  - python-graphviz
  - python-kaleido
  - scipy
  - seaborn
  - setuptools
  - watermark
  - xlrd