[project]
authors = [
    "Chris Fonnesbeck <fonnesbeck@gmail.com>",
]
channels = ["conda-forge"]
description = "Introduction to Bayesian Statistics with PyMC"
name = "intro_pymc"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "*"
hvplot = "*"
ipython = "*"
ipywidgets = "*"
jupyter_client = "*"
jupyter_core = "*"
jupyterlab = "*"
numpy = "*"
pandas = "*"
patsy = "*"
pip = "*"
polars = "*"
pyarrow = "*"
pymc = "*"
pydot = "*"
python-graphviz = "*"
scipy = "*"
seaborn = "*"
setuptools = "*"
watermark = "*"
preliz = ">=0.12.0,<0.13"
altair = ">=5.5.0,<6"
nutpie = ">=0.13.2,<0.14"
numba = ">=0.60.0,<0.61"
xlrd = ">=2.0.1,<3"
jupyter_bokeh = ">=4.0.5,<5"
plotly = ">=6.0.1,<7"
blackjax = ">=1.2.4,<2"
python-kaleido = "*"
jax = ">=0.5.2,<0.6"
numpyro = ">=0.18.0,<0.19"
pymc-extras = ">=0.2.5,<0.3"
marimo = ">=0.13.6,<0.14"
python-lsp-server = ">=1.12.2,<2"
pyobsplot = ">=0.5.2,<0.6"

